version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - apt-get update
      - apt-get install -y maven

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn test
artifacts:
  files:
    - target/*.jar

