version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - apt-get update
      - apt-get install -y maven

  build:
    commands:
      - echo Build started on `date`

artifacts:
  files:
    - target/*.jar  # Include the generated JAR files as artifacts
